[tool.poetry]
name = "electronics-store"
version = "0.1.0"
packages = [{include = "app", from = "."}]

[tool.poetry.dependencies]
python = "^3.13"
celery = "5.3.6"
Django = "6.0.2"
psycopg2-binary = "2.9.11"
redis = "7.2.1"
concurrent-log-handler = "0.9.28"
python-dotenv = "1.2.2"
gunicorn = "25.1.0"
djangorestframework = "3.16.0"

[tool.poetry.group.dev.dependencies]
ruff = "0.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py313"
line-length = 79
indent-width = 4
include = ["app/**/*.py"]
exclude = ["**/migrations/*.py",]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN003", "ANN204",
    "D100", "D101", "D104", "D105", "D107", "D205", "D106",
    "D200", "D203", "D212", "D417", "D413",
    "EM101", "EM102",
    "TRY003", "TRY300", "TRY400",
    "PLR0913", "G004", "INP001", "UP046",
    "FAST002", "RET504", "A002"
]

[tool.ruff.lint.per-file-ignores]
"app/manage.py" = ["PLC0415"]
"app/core/celery.py" = ["D103", "ANN002"]