# Generated by Django 6.0.2 on 2026-05-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='node',
            new_name='store',
        ),
    ]
