# Generated by Django 6.0.2 on 2026-05-24 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_node_employee_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
