# Generated by Django 6.0.2 on 2026-05-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',)},
        ),
    ]
