# Generated by Django 6.0.2 on 2026-05-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',)},
        ),
    ]
