# Generated by Django 6.0.2 on 2026-05-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_release',
            new_name='release_date',
        ),
    ]
